MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
    OUT_CHANNELS: 128
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    POST_NMS_TOPK_TEST: 50
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
  MASK_ON: True
  MASKIOU_ON: True
  ROI_HEADS:
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 2
    CONV_DIM: 128
  ROI_MASKIOU_HEAD:
    NUM_CONV: 2
    CONV_DIM: 128
DATASETS:
  TRAIN: ("publaynet_train",)
  TEST: ("publaynet_val",)
SOLVER:
  CHECKPOINT_PERIOD: 1000
  IMS_PER_BATCH: 24
  BASE_LR: 0.001  # Note that RetinaNet uses a different default learning rate
  STEPS: (0, 500000)
  MAX_ITER: 500000
INPUT:
  MIN_SIZE_TRAIN: (580, 600)
  MAX_SIZE_TRAIN: 1000
  MIN_SIZE_TEST: 600
  MAX_SIZE_TEST: 1000
DATALOADER:
  NUM_WORKERS: 16
